// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlu6SaX2s8LWvEKmhs1PMwC0ZQ0M_U5FU',
    appId: '1:849880119544:web:e2b6c15eda7f1254d8e30d',
    messagingSenderId: '849880119544',
    projectId: 'zimo-app-65df1',
    authDomain: 'zimo-app-65df1.firebaseapp.com',
    storageBucket: 'zimo-app-65df1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXboFRS-0bS-XBHxf_oaRUZCPzIAmfQcE',
    appId: '1:849880119544:android:fa285244a38fdf91d8e30d',
    messagingSenderId: '849880119544',
    projectId: 'zimo-app-65df1',
    storageBucket: 'zimo-app-65df1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB302cwGZVEsirh1JnYakYeoSasMdXxgYE',
    appId: '1:849880119544:ios:90b1f3f71910532bd8e30d',
    messagingSenderId: '849880119544',
    projectId: 'zimo-app-65df1',
    storageBucket: 'zimo-app-65df1.firebasestorage.app',
    iosBundleId: 'com.example.zimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB302cwGZVEsirh1JnYakYeoSasMdXxgYE',
    appId: '1:849880119544:ios:90b1f3f71910532bd8e30d',
    messagingSenderId: '849880119544',
    projectId: 'zimo-app-65df1',
    storageBucket: 'zimo-app-65df1.firebasestorage.app',
    iosBundleId: 'com.example.zimo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlu6SaX2s8LWvEKmhs1PMwC0ZQ0M_U5FU',
    appId: '1:849880119544:web:5e2478b0248e9378d8e30d',
    messagingSenderId: '849880119544',
    projectId: 'zimo-app-65df1',
    authDomain: 'zimo-app-65df1.firebaseapp.com',
    storageBucket: 'zimo-app-65df1.firebasestorage.app',
  );
}
